### ISSUE TITLE
Rename to dask-csp?

### ISSUE THREAD

**Issue by mrocklin** [jacobtomlinson/dask-cloud#2]
I can imagine that the term `dask-cloud` might mean a number of things in the future.  This seems like a fairly valuable term long-term.  From a marketing perspective we might want to hold off on claiming that name with this project until this becomes widely used.

**Comment by jacobtomlinson** [comment]
I started with `dask-csp` and felt that it wasn't clear what it was so renamed. 

Happy to change back though as I agree about the value of `dask-cloud`.

**Comment by mrocklin** [comment]
Agreed about "csp".  There might be some other solution that is both more accessible to novice users and doesn't take the prominent name.  Let's both ponder a bit.

**Comment by mrocklin** [comment]
Also cc'ing @jcrist , who might have thoughts

**Comment by jcrist** [comment]
I had to think for a minute to figure out what `csp` meant. This term may have more meaning to others though.

No immediate thoughts on a better name, but I'm not sure `dask-cloud` is that terrible. If a company started a `dask-cloud` service, they'd have to call it something more specific due to our governance documents. Other servers like `dask-gateway` likely have better more specific names as well.

**Comment by jcrist** [comment]
`dask-cloudprovider`?

**Comment by mrocklin** [comment]
I could imagine us hosting a cloud service as a non-profit under NumFOCUS, similar to how pangeo operates today.

**Comment by mrocklin** [comment]
dask-cloudprovider seems good to me.  I definitely prefer it to either dask-cloud or dask-csp (Jim's reaction of "huh?" is probably all the evidence we need that it's a bad name :) )

**Comment by jacobtomlinson** [comment]
I like `dask-cloudprovider` also. I'll go with that.
